name: Scheduled Freeze Check

on:
  workflow_dispatch:
    inputs:
      action_type:
        description: 'Action type (freeze or unfreeze)'
        required: true
        default: 'freeze'
      target_branches:
        description: 'Comma-separated list of target branches to check for freezes (e.g., main,dev)'
        required: true
        default: 'main,dev'
      time_zone:
        description: 'Time zone for the freeze periods (e.g., Europe/Paris, America/New_York)'
        required: false
        default: 'Europe/Paris'
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

permissions:
  pull-requests: write
  statuses: write

jobs:
  check-freeze:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Check for freeze period and fail PRs if necessary
      run: |
        echo "Checking action type and processing PRs accordingly..."
        node .github/scripts/check-freeze.js "${{ github.event.inputs.action_type }}" "${{ github.event.inputs.target_branches }}" "${{ github.event.inputs.time_zone }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
