name: Manual Freeze Check

on:
  workflow_dispatch:
    inputs:
      freeze_periods:
        description: 'Comma-separated list of freeze periods in the format start1:end1,start2:end2,... (e.g., 2024-06-01T00:00:2024-06-01T01:00,2024-12-20T12:00:2024-12-20T13:00)'
        required: true
      target_branches:
        description: 'Comma-separated list of target branches to check for freezes (e.g., main,dev)'
        required: true
        default: 'main,staging'

permissions:
  pull-requests: write
  statuses: write

jobs:
  check-freeze:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Check for freeze period and fail PRs if within freeze period
      run: |
        echo "Checking for freeze period and failing PRs if necessary..."
        node .github/scripts/check-freeze.js '${{ github.event.inputs.freeze_periods }}' '${{ github.event.inputs.target_branches }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
