name: Manual Freeze Check

on:
  workflow_dispatch:
    inputs:
      freeze_periods:
        description: 'Comma-separated list of freeze periods in the format start1:end1,start2:end2,... (e.g., 2024-06-01:2024-06-15,2024-12-20:2025-01-05)'
        required: true

jobs:
  check-freeze:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Check for freeze period
      id: check-freeze
      run: |
        echo "Checking for freeze period..."
        node .github/scripts/check-freeze.js
      env:
        FREEZE_PERIODS: ${{ github.event.inputs.freeze_periods }}

    - name: Get open pull requests
      id: pr
      uses: octokit/request-action@v2
      with:
        route: GET /repos/${{ github.repository }}/pulls

    - name: Fail PRs if within freeze period
      if: steps.check-freeze.outputs.freeze == 'true'
      run: |
        echo "Failing all open pull requests..."
        prs=$(jq -r '.[] | .number' <<<"${{ steps.pr.outputs.data }}")
        for pr in $prs; do
          gh api repos/${{ github.repository }}/statuses/$pr \
            -f state=error \
            -f description="Code freeze in effect" \
            -f context="freeze-check"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
